# Generated by Django 5.0.6 on 2024-06-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showing', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=30),
        ),
    ]
