# Generated by Django 5.0.6 on 2024-06-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showing', '0003_alter_coin_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price_change_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
