# Generated by Django 5.0.6 on 2024-06-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showing', '0006_alter_coin_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='coin',
            name='price_change_percentage',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='volume',
            field=models.CharField(max_length=30),
        ),
    ]
